package com.gplayer;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.google.appengine.api.datastore.Key;

@Entity
public class ClientSessionData
{
    /*
     * Autogenerated primary key
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Key key;
    
    private List<Song> mDiffList;
    private int mCurrentSong;
   
    public List<Song> getDiffList()
    {
        return mDiffList;
    }

    public void setDiffList(List<Song> diffList)
    {
        this.mDiffList = diffList;
    }

    public int getCurrentSong()
    {
        return mCurrentSong;
    }

    public void setCurrentSong(int currentSong)
    {
        this.mCurrentSong = currentSong;
    }
    
    

}
